#!/bin/bash

# проверка сети на минималках
# несколько проверок на заполненность строк и ответов

cat << _EOF_ 
"Привет $USER! Проверим Интернет?"
_EOF_


read -p "Напиши yes или no: " ANSWER

SCRIPT="ping -c 10 <ADDRESS>"

if [ -z "$ANSWER" ]; then
echo "Ничего не набрал, выхожу!" >&2
exit 1
fi
if [ "$ANSWER" == "yes" ]; then
echo "Проверяю, подожди"
$SCRIPT
elif [ "$ANSWER" == "no" ]; then
echo "Ок, в другой раз!"
else
echo "Был другой ответ, пока."
fi
